### ISSUE TITLE
Remove pam_ldap/pam_nss configuration support

### ISSUE THREAD

**Issue by Firstyear** [yast/yast-auth-client#82]
pam_ldap and nss_ldap have not been maintained since 2014. We should not be allowing new configurations of these modules, as I would like to begin to remove these in openSUSE.

Instead all ldap/krb/ad clients should use the supported and secure sssd module by default.

**Comment by ancorgs** [comment]
Since the yast2-auth-client package is developed and maintained by the Samba Team at SUSE, instead of the core YaST Team, I'm adding the "other-maintainer" label to this in order to help filtering the various list of issues.
