### ISSUE TITLE
Change LDAP auth client setup from binddn and bindpwd to rootbinddn and 600 /etc/ldap.secret

### ISSUE THREAD

**Issue by MuGrU** [yast/yast-auth-client#97]
Hello Team,

I would like to suggest to make this change to improve the security for LDAP Client auth setup, I had a look at the code and does not seem to be so hard to change that, this is related to #70  as well.

The suggestion it is to change the binddn from /etc/ldap.conf to rootbinddn, remove the bindpwd option from ldap.conf and create a file with 0600 as /etc/ldap.secret with the password in clear text.

I would like to start to contribute with some OpenSUSE project and I can give a try if you want.

**Comment by ancorgs** [comment]
Since the yast2-auth-client package is developed and maintained by the Samba Team at SUSE, instead of the core YaST Team, I'm adding the "other-maintainer" label to this in order to help filtering the various list of issues.

**Comment by MuGrU** [comment]
> Since the yast2-auth-client package is developed and maintained by the Samba Team at SUSE, instead of the core YaST Team, I'm adding the "other-maintainer" label to this in order to help filtering the various list of issues.

Thank you @ancorgs , In fact after some tests and a chat with some colleagues I figure out it will breaks ldap_pam lib once it needs read, so indeed the /etc/ldap.conf with binddn and bindpwd looks a better solution.
